### ISSUE TITLE
After registration for employers and student Toastr

### ISSUE THREAD

**Issue by charlesjavelona** [UnivJobs/univjobs-main#21]
Please change the wording for the Toastr when student or employers move around the app without confirmation of email and profile creation into:

"Before you can move on, we need you to finish your profile & confirm the email we sent you.
Thanks!"

**Comment by stemmlerjs** [comment]
Yeah, this is the email verification token flow. 

Just realizing that this wasn't actually properly flowed out. The APIs work, just need to connect everything with a good UI flow.

**Comment by stemmlerjs** [comment]
This is complete. Employers and Students need to complete their profile and confirm the email before being able to move onto the rest of the application.
