### ISSUE TITLE
In employer profile. Turn off location validator if work is remote

### ISSUE THREAD

**Issue by charlesjavelona** [UnivJobs/univjobs-main#22]
<img width="1280" alt="screen shot 2017-06-20 at 4 13 34 pm" src="https://user-images.githubusercontent.com/7959179/27353813-748e7066-55d3-11e7-892a-759da8c806eb.png">

**Comment by stemmlerjs** [comment]
Done. Disables the Job Location field when you select Remote Work.

![image](https://user-images.githubusercontent.com/6892666/27490235-7aea17be-580b-11e7-9ddf-01d6d44d0d1e.png)
