### ISSUE TITLE
Change the email on the error of student signup

### ISSUE THREAD

**Issue by charlesjavelona** [UnivJobs/univjobs-main#23]
Make the error red and change the email to univjobscanada@gmail.com

<img width="1280" alt="screen shot 2017-06-20 at 4 44 42 pm" src="https://user-images.githubusercontent.com/7959179/27355208-25c3ff82-55d8-11e7-837b-4ff73c2fef24.png">

**Comment by stemmlerjs** [comment]
Done. Resolved with https://github.com/UnivJobs/univjobs-main/issues/25
