### ISSUE TITLE
Review listing needs CSS work on the card titles.

### ISSUE THREAD

**Issue by charlesjavelona** [UnivJobs/univjobs-main#24]
<img width="1280" alt="screen shot 2017-06-20 at 7 56 57 pm" src="https://user-images.githubusercontent.com/7959179/27361134-5a0ae3bc-55f3-11e7-8f0b-7134dbd73034.png">

**Comment by stemmlerjs** [comment]
![image](https://user-images.githubusercontent.com/6892666/27488210-3dd09a9e-5804-11e7-9a16-a45614c2a58f.png)
