### ISSUE TITLE
My Applicants page needs to show job posting info to refer back to job posting

### ISSUE THREAD

**Issue by charlesjavelona** [UnivJobs/univjobs-main#36]
Currently the employer can see the applicants every dropdown changes.
<img width="1280" alt="screen shot 2017-06-26 at 4 28 28 pm" src="https://user-images.githubusercontent.com/7959179/27558910-b5a45c9c-5a8c-11e7-85f3-9c9080c30731.png">

 
As an employer, I want to reference the job I made whenever I screen students to see if they closely match the job info I have something close to like this but for jobs would be useful.
<img width="1280" alt="screen shot 2017-06-26 at 4 37 32 pm" src="https://user-images.githubusercontent.com/7959179/27559239-d03c7b60-5a8d-11e7-93a5-01d256d737c2.png">

**Comment by charlesjavelona** [comment]
To do:
- [ ] Get design from George of the dropdown, and where to click to show the side bar

**Comment by charlesjavelona** [comment]
[jobsliderinfo.pdf](https://github.com/UnivJobs/univjobs-main/files/1107450/jobsliderinfo.pdf)

**Comment by stemmlerjs** [comment]
![image](https://user-images.githubusercontent.com/6892666/27758440-d73a4742-5de1-11e7-8401-bae5f9868202.png)

![image](https://user-images.githubusercontent.com/6892666/27758441-dee9279c-5de1-11e7-8225-d0e0482ae324.png)
