### ISSUE TITLE
Settings Page for Students

### ISSUE THREAD

**Issue by stemmlerjs** [UnivJobs/univjobs-main#42]
- If they get hired for a job, we should let them know that they have the ability to "Appear Invisible" (maybe do this in an email?) to employers. This option should be available in the Settings page for a student.
- On Hire for a job, this should inform all of the other employers for jobs that this student has applied to that the student has been hired at another job. (this will likely be done in the same block of code that we send emails to all of the other students who didn't get the job).

Make the settings page look something like Google's Settings page in Google Chrome where it actually expands on the options with prose so you can understand why you may want to change the settings.

**Comment by charlesjavelona** [comment]
TO DO FOR CHARLES:
 - [ ] Make front-end ui for settings page

**Comment by stemmlerjs** [comment]
Example of supplementary information with settings so that you kinda understand what the setting does in the application.

![image](https://user-images.githubusercontent.com/6892666/27621320-f501f310-5b9d-11e7-9764-0ea9f5b4a769.png)

**Comment by charlesjavelona** [comment]
Pseudocode:

When student user goes to settings
  Render card with info and toggle button state
  If user clicks toggle button 
    ask user are they sure ? 
     if user clicks yes
       turn on or off is_active attribute
       if user turns off is_active attribute
         delete all traces of user in invite and applied jobs
       else
          show user as active in invites and allow them to do normal things
     else
       none
  else
       none
