### ISSUE TITLE
Install Google Analytics

### ISSUE THREAD

**Issue by stemmlerjs** [UnivJobs/univjobs-main#44]
https://github.com/rangle/redux-beacon/tree/master/examples/google-analytics
http://blog.rangle.io/tracking-form-completion-in-google-analytics-with-redux/
https://analytics.google.com/analytics/web/#embed/reporthome/a75925209w114404868p119600816/

**Comment by charlesjavelona** [comment]
Installed basic google analytics using react-redux-beacon by rangle.io
In the future will be using redux to track user actions as well consider in the future Hot Jar and FullStory

https://rangle.github.io/redux-beacon/docs/targets/google-analytics.html
https://github.com/rangle/redux-beacon/blob/master/examples/google-analytics/index.js
https://rangle.github.io/redux-beacon/docs/quick-start/redux-users.html
